name = "Unitary"
uuid = "75ebfc8e-976a-11e9-26c7-f5346d660b1d"
authors = ["Pevnak <pevnak@gmail.com>"]
version = "0.1.0"

[deps]
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"