name = "Unitary"
uuid = "75ebfc8e-976a-11e9-26c7-f5346d660b1d"
authors = ["Pevnak <pevnak@gmail.com>"]
version = "0.1.0"

[deps]
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
FillArrays = "^0.9"
Flux = "^0.11"
NNlib = "^0.7"
SpecialFunctions = "^1.0"
Zygote = "~0.5.4"
julia = "^1.4"
